spring:
  datasource:
    username: ${DB_USER:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_SCHEMA:tasco}
    password: ${DB_PASS:123456}
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'false'

  main:
    banner-mode: off
    web-application-type: none
    lazy-initialization: true

  application:
    name: tasco

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

logging:
  level:
    org.springframework: ERROR
    org.hibernate: ERROR
    root: off

server:
  error:
    include-message: always